apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ap5skosfi-python
  janus-idp.io/tekton: ap5skosfi-python
  backstage.io/kubernetes-id: ap5skosfi-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ap5skosfi-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
