apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ap5skosfi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ap5skosfi-python 
  name: ap5skosfi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ap5skosfi-python 
